"""simplify assistant model

Revision ID: ad855282e5c2
Revises: 70860870412e
Create Date: 2026-01-25 12:35:02.711868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad855282e5c2'
down_revision: Union[str, None] = '70860870412e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding new columns with nullable=True first to avoid issues with existing data
    op.add_column(
        'assistants',
        sa.Column('is_active', sa.Boolean(), nullable=True)
    )
    op.add_column(
        'assistants',
        sa.Column('last_checked_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'assistants',
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )

    # Populate new columns with default values where necessary
    op.execute(
        "UPDATE assistants SET is_active = true WHERE is_active IS NULL"
    )
    op.execute(
        "UPDATE assistants SET created_at = NOW() WHERE created_at IS NULL"
    )

    # Alter columns to set nullable=False after populating data
    op.alter_column('assistants', 'is_active', nullable=False)
    op.alter_column('assistants', 'created_at', nullable=False)
    
    # Create index on name column
    op.create_index(op.f('ix_assistants_name'), 'assistants', ['name'], unique=True)

    # Drop obsolete columns
    op.drop_column('assistants', 'provider')
    op.drop_column('assistants', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('assistants', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_assistants_name'), table_name='assistants')
    op.drop_column('assistants', 'created_at')
    op.drop_column('assistants', 'last_checked_at')
    op.drop_column('assistants', 'is_active')
    # ### end Alembic commands ###
