"""move_assistant_id

Revision ID: cb942589659b
Revises: 5464a97929c5
Create Date: 2026-01-31 12:42:07.577940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb942589659b'
down_revision: Union[str, None] = '5464a97929c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_assistant_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'assistant_id')
    op.add_column('messages', sa.Column('assistant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'assistants', ['assistant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'assistant_id')
    op.add_column('chats', sa.Column('assistant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chats_assistant_id_fkey'), 'chats', 'assistants', ['assistant_id'], ['id'])
    # ### end Alembic commands ###
